#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wireless-regdb-master
Version  : 2022.02.18
Release  : 12
URL      : https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/snapshot/wireless-regdb-master-2022-02-18.tar.gz
Source0  : https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/snapshot/wireless-regdb-master-2022-02-18.tar.gz
Summary  : Linux wireless regulatory database
Group    : Development/Tools
License  : ISC
Requires: wireless-regdb-master-license = %{version}-%{release}
Requires: wireless-regdb-master-man = %{version}-%{release}

%description
This package contains the wireless regulatory database used by all
cfg80211 based Linux wireless drivers. The wireless database being
used is maintained by Seth Forshee.
http://wireless.kernel.org/en/developers/Regulatory/

%package license
Summary: license components for the wireless-regdb-master package.
Group: Default

%description license
license components for the wireless-regdb-master package.


%package man
Summary: man components for the wireless-regdb-master package.
Group: Default

%description man
man components for the wireless-regdb-master package.


%prep
%setup -q -n wireless-regdb-master-2022-02-18
cd %{_builddir}/wireless-regdb-master-2022-02-18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1645564218
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}  PYTHON=/usr/bin/python install DESTDIR=%{buildroot}


%install
export SOURCE_DATE_EPOCH=1645564218
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wireless-regdb-master
cp %{_builddir}/wireless-regdb-master-2022-02-18/LICENSE %{buildroot}/usr/share/package-licenses/wireless-regdb-master/ecc93a54e4f154e77e88c5cc2c975bfb72916fa0
cp %{_builddir}/wireless-regdb-master-2022-02-18/debian-example/copyright %{buildroot}/usr/share/package-licenses/wireless-regdb-master/81e09d9b5b8dfbf0f7adc82479395bd00f26839b
%make_install FIRMWARE_PATH=/usr/lib/firmware LSB_ID="clr"

%files
%defattr(-,root,root,-)
/usr/lib/crda/pubkeys/sforshee.key.pub.pem
/usr/lib/crda/regulatory.bin
/usr/lib/firmware/regulatory.db
/usr/lib/firmware/regulatory.db.p7s

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wireless-regdb-master/81e09d9b5b8dfbf0f7adc82479395bd00f26839b
/usr/share/package-licenses/wireless-regdb-master/ecc93a54e4f154e77e88c5cc2c975bfb72916fa0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/regulatory.bin.5.gz
/usr/share/man/man5/regulatory.db.5.gz
