#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wireless-regdb-master
Version  : 2017.12.23
Release  : 5
URL      : https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/snapshot/wireless-regdb-master-2017-12-23.tar.gz
Source0  : https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/snapshot/wireless-regdb-master-2017-12-23.tar.gz
Summary  : Linux wireless regulatory database
Group    : Development/Tools
License  : ISC
Requires: wireless-regdb-master-doc
BuildRequires : python-core
Patch1: py3.patch

%description
This package contains the wireless regulatory database used by all
cfg80211 based Linux wireless drivers. The wireless database being
used is maintained by Seth Forshee.
http://wireless.kernel.org/en/developers/Regulatory/

%package doc
Summary: doc components for the wireless-regdb-master package.
Group: Documentation

%description doc
doc components for the wireless-regdb-master package.


%prep
%setup -q -n wireless-regdb-master-2017-12-23
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523111981
make  %{?_smp_mflags} PYTHON=/usr/bin/python2 install DESTDIR=%{buildroot}

%install
export SOURCE_DATE_EPOCH=1523111981
rm -rf %{buildroot}
%make_install FIRMWARE_PATH=/usr/lib/firmware LSB_ID="clr"

%files
%defattr(-,root,root,-)
/usr/lib/crda/pubkeys/sforshee.key.pub.pem
/usr/lib/crda/regulatory.bin
/usr/lib/firmware/regulatory.db
/usr/lib/firmware/regulatory.db.p7s

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man5/*
